services:
  video-site-91:
    image: ghcr.io/kimjioo/91:latest
    container_name: video-site-91
    restart: always
    ports:
      - "9191:9191"
    volumes:
      # 1. 映射整个数据目录（完美包含 .db 数据库和 previews 文件夹）
      - ./data:/opt/video-site-91/data
      # 2. 单独映射核心配置文件
      - ./config.yaml:/opt/video-site-91/config.yaml
    environment:
      - FRONTEND_PORT=9191
