services:
  video-site-91:
    image: ghcr.io/kimjioo/91:latest
    container_name: video-site-91
    restart: always
    ports:
      - "9191:8080"  # 保持之前的端口设置不变
    volumes:
      # 现在只需要这一个映射就够了，数据和配置都在里面
      - ./data:/opt/video-site-91/data
    environment:
      - FRONTEND_PORT=9191
      # 告诉程序，配置文件现在放在 data 目录下了！
      - VIDEO_CONFIG=/opt/video-site-91/data/config.yaml
